networks:
  app-network:
    driver: bridge

services:
  openmaic:
    image: kof0098c/openmaic:latest
    container_name: openmaic
    ports:
      - "13033:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network